"""storage map table

Revision ID: 540ceb27b84e
Revises: b126166fa136
Create Date: 2019-12-06 01:22:07.039192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540ceb27b84e'
down_revision = 'b126166fa136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('longURL', sa.String(length=200), nullable=False),
    sa.Column('shortURL', sa.String(length=100), nullable=False),
    sa.Column('activated', sa.DateTime(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('longURL')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storage_map')
    # ### end Alembic commands ###
